import { existsSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, expect, it } from "vitest";

import manifest from "@/app/manifest";

const projectRoot = join(__dirname, "..", "..");
const serviceWorkerSource = readFileSync(
  join(projectRoot, "public", "sw.js"),
  "utf8",
);

function extractAppShellUrls(source: string): string[] {
  const listMatch = source.match(/APP_SHELL_URLS = \[([\s\S]*?)\];/);
  if (!listMatch) {
    throw new Error("APP_SHELL_URLS not found in public/sw.js");
  }

  const urls = [...listMatch[1].matchAll(/"([^"]+)"/g)].map((match) => match[1]);
  return source.includes("OFFLINE_URL,") ? ["/offline", ...urls] : urls;
}

describe("service worker precache manifest", () => {
  const appShellUrls = extractAppShellUrls(serviceWorkerSource);

  it("only precaches static files that actually exist in public/", () => {
    const fileUrls = appShellUrls.filter((url) => url.includes("."));
    expect(fileUrls.length).toBeGreaterThan(0);

    for (const url of fileUrls) {
      if (url === "/manifest.webmanifest") {
        // Generated by Next.js from app/manifest.ts at build time.
        continue;
      }
      expect(existsSync(join(projectRoot, "public", url)), `${url} missing from public/`).toBe(
        true,
      );
    }
  });

  it("precaches every icon referenced by the web app manifest", () => {
    const manifestIcons = (manifest().icons ?? []).map((icon) => icon.src);
    expect(manifestIcons.length).toBeGreaterThan(0);

    for (const icon of manifestIcons) {
      expect(appShellUrls, `${icon} is not precached by public/sw.js`).toContain(icon);
    }
  });

  it("keeps the offline fallback route in the precache list", () => {
    expect(appShellUrls).toContain("/offline");
  });

  it("caches visited pages so navigation works offline", () => {
    const navigateHandler = serviceWorkerSource.slice(
      serviceWorkerSource.indexOf('request.mode === "navigate"'),
    );
    expect(navigateHandler).toContain("cache.put(request");
    expect(navigateHandler).toContain("cache.match(request)");
  });
});
