export const storeNames = {
  meta: "meta",
  userProfiles: "userProfiles",
  accounts: "accounts",
  transactions: "transactions",
  captureEnvelopes: "captureEnvelopes",
  captureReviewItems: "captureReviewItems",
  correctionLogs: "correctionLogs",
  transactionRules: "transactionRules",
  recurringObligations: "recurringObligations",
  monthCloses: "monthCloses",
  categories: "categories",
  counterparties: "counterparties",
  goals: "goals",
  budgets: "budgets",
  investmentProfiles: "investmentProfiles",
  imports: "imports",
  resources: "resources",
  syncProfiles: "syncProfiles",
  syncOutbox: "syncOutbox",
  items: "items",
  plannedPurchases: "plannedPurchases",
  transactionLineItems: "transactionLineItems",
} as const;

export type StoreName = (typeof storeNames)[keyof typeof storeNames];
